apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: mern-app
spec:
  selector:
    app: job-app-backend
  ports:
    - protocol: TCP
      port: 5002         # port que le frontend utilise
      targetPort: 5002   # port r√©el du pod backend
  type: ClusterIP
