apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: mern-app
spec:
  selector:
    app: job-app-backend
  ports:
    - protocol: TCP
      port: 5001       # Port que le frontend utilise
      targetPort: 5002 # Port sur lequel le pod backend Ã©coute
  type: ClusterIP
