apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: mern-app
spec:
  type: NodePort
  selector:
    app: job-app-frontend
  ports:
    - protocol: TCP
      port: 80          # Port exposé par le service
      targetPort: 80    # ⚡ DOIT correspondre au port du pod
      nodePort: 31216   # Tu peux garder le même NodePort
