apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: mern-app
spec:
  type: ClusterIP
  selector:
    app: job-app-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31216
